services:
  selenoid:
    image: aerokube/selenoid:1.11.3
    container_name: selenoid
    networks:
      - selenoid-network
    ports:
      - "4444:4444"
    environment:
      - DOCKER_API_VERSION=1.44
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - selenoid-config:/etc/selenoid:ro
    command: ["-conf", "/etc/selenoid/browsers.json", "-limit", "5", "-container-network", "selenoid-network"]

  tests:
    build: .
    container_name: tests
    networks:
      - selenoid-network
    depends_on:
      - selenoid
    environment:
      SELENOID_URL: http://selenoid:4444/wd/hub
    volumes:
      - maven-repo:/root/.m2
      - ./target:/app/target
    command: ["sh", "-c", "mvn test && sleep 10"]

networks:
  selenoid-network:
    name: selenoid-network
    driver: bridge

volumes:
  maven-repo:
  selenoid-config:
    external: true

